baseURL: "/"
DefaultContentLanguage: "bn"
defaultContentLanguageInSubdir: "false"
enableMissingTranslationPlaceholders: "false"
timeZone: "Asia/Dhaka"
# enableGitInfo: true
# googleAnalytics: "G-3NFDT41J8E"

paginate: 6

languages:
  bn:
    disabled: false
    # contentDir: content/bn/
    languageCode: bn-BD
    languageDirection: ltr
    languageName: বাংলা
    title: বাংলা উইকিসংযোগ
    weight: 1
    params:
      subtitle: "উইকিমিডিয়ানদের একটি সম্মিলিত উদ্যোগ"
      author:
        name: বাংলা উইকিসংযোগ টিম
        jobtitle: উইকিমিডিয়া সম্প্রদায়
      description: বাংলা উইকিসংযোগ একটি সম্মিলিত প্রচেষ্টা যা বাংলা ভাষার উইকিপিডিয়া ও অন্যান্য উইকিমিডিয়া প্রকল্পে অবদান বাড়াতে লক্ষ্য করে।
      cse: 458e08bf4d1094c8e
  en:
    disabled: false
    # contentDir: content/en/
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    title: Bangla WikiConnect
    weight: 2
    params:
      subtitle: "A collaborative initiative by Wikimedians"
      author:
        name: Bangla WikiConnect Team
        jobtitle: Wikimedia Community
      description: Bangla WikiConnect is a collaborative initiative focused on expanding content in the Bengali language on Wikipedia and other Wikimedia projects.
      cse: 02da3ac110b6e40d1

Params:
  defaultColorMode: "light"
  activateColorModeToogler: true
  activatejQuery: false
  activateGlobalMenu: false
  useBootstrapMod: true
  useBootstrapIcons: true
  userBootstrapBundleJS: true
  BootstrapCDNVersion: "5.3.3"
  defaultLang: bn
  google_site_verification: "0J8IfuFx-q_dRuc9I1q0tcVBKAMOTAN3gr27m5OwKzQ"
  fb_app_id: ""
  meta:
    name: Bangla WikiConnect
    alternateName: "WikiConnect"
  author:
    name: Bangla WikiConnect Team
    jobtitle: Wikimedia Contributors
    url: "https://meta.wikimedia.org/wiki/Bangla_WikiConnect"
    email: connect@bnwp.org
    locality: Bangladesh
  social:
    facebook: "https://facebook.com/banglawikiconnect"
    linkedin: "https://linkedin.com/in/banglawikiconnect"
    youtube: "https://youtube.com/@banglawikiconnect"
    github: "https://github.com/bnwp"
    wikipedia: "https://meta.wikimedia.org/wiki/Bangla_WikiConnect"
    #twitter: banglawikiconnect
  phone: "+880 1601660666"
  picture: /assets/images/Bangla_WikiConnect_Logo.jpg
  github:
    user: bnwp
    repo: bnwp.github.io
    branch: main
  og:
    image: /assets/images/Bangla_WikiConnect_og_image.png

taxonomies:
  tag: tags
  team: teams

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
outputs:
  home: ["HTML", "RSS", "JSON"]
