# Netlify configuration for Hugo site deployment
# Place this file in the repository root as netlify.toml

[build]
  publish = "public"
  command = "hugo --minify --baseURL $DEPLOY_PRIME_URL"

[build.environment]
  HUGO_VERSION = "0.120.4"

[context.production]
  command = "hugo --minify --baseURL https://your-custom-domain.com"

[context.deploy-preview]
  command = "hugo --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --minify --baseURL $DEPLOY_PRIME_URL"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://connect.facebook.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self';"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules (if needed)
[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404